# Generated by Django 5.1.2 on 2024-10-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emai', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('Reservations_date', models.DateField(auto_now_add=True)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('reservation_status', models.CharField(max_length=20)),
                ('reservation_description', models.TextField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('room_number', models.IntegerField()),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='reservations',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rooms'),
        ),
    ]
